site_name: Python Time & Space Complexity
site_description: Comprehensive documentation of time and space complexity for Python built-ins and standard library
site_url: https://pythoncomplexity.com

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.path
    - toc.integrate
    - content.code.copy
    - search.suggest
    - search.highlight
  palette:
    - scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: indigo
      toggle:
        icon: material/lightbulb
        name: Switch to light mode

nav:
  - Home: index.md
  - Built-in Types:
    - Overview: builtins/index.md
    - Lists: builtins/list.md
    - Dictionaries: builtins/dict.md
    - Sets: builtins/set.md
    - Tuples: builtins/tuple.md
    - Strings: builtins/str.md
    - Bytes & Bytearray: builtins/bytes.md
    - Frozenset: builtins/frozenset.md
    - Range: builtins/range.md
    - Integer: builtins/int.md
    - Float: builtins/float.md
    - Boolean: builtins/bool.md
  - Built-in Functions:
    - Length: builtins/len.md
    - Maximum: builtins/max.md
    - Minimum: builtins/min.md
    - Sum: builtins/sum.md
    - Map: builtins/map.md
    - Filter: builtins/filter.md
    - Zip: builtins/zip.md
    - Sorted: builtins/sorted.md
    - Enumerate: builtins/enumerate.md
    - All: builtins/all.md
    - Aiter: builtins/aiter.md
    - Anext: builtins/anext.md
    - Any: builtins/any.md
    - Absolute: builtins/abs.md
    - Power: builtins/pow.md
    - Round: builtins/round.md
    - Ord: builtins/ord.md
    - Chr: builtins/chr.md
    - Reversed: builtins/reversed.md
    - Divmod: builtins/divmod.md
    - Slice: builtins/slice.md
    - Iter: builtins/iter.md
    - Issubclass: builtins/issubclass.md
    - Open: builtins/open.md
    - Hash: builtins/hash.md
    - Format: builtins/format.md
    - Isinstance: builtins/isinstance.md
    - Next: builtins/next.md
    - Input: builtins/input.md
    - Id: builtins/id.md
    - Globals: builtins/globals.md
    - Locals: builtins/locals_func.md
    - Print: builtins/print.md
    - Help: builtins/help.md
    - Repr: builtins/repr.md
    - Ascii: builtins/ascii.md
    - Eval: builtins/eval.md
    - Exec: builtins/exec.md
    - Compile: builtins/compile.md
    - Hex: builtins/hex.md
    - Bin: builtins/bin.md
    - Breakpoint: builtins/breakpoint.md
    - Oct: builtins/oct.md
    - Type: builtins/type_func.md
    - Callable: builtins/callable.md
    - Bool: builtins/bool_func.md
    - Int: builtins/int_func.md
    - Float: builtins/float_func.md
    - Str: builtins/str_func.md
    - Bytes: builtins/bytes_func.md
    - List: builtins/list_func.md
    - Dict: builtins/dict_func.md
    - Set: builtins/set_func.md
    - Frozenset: builtins/frozenset_func.md
    - Tuple: builtins/tuple_func.md
    - Bytearray: builtins/bytearray_func.md
    - Complex: builtins/complex_func.md
    - Memoryview: builtins/memoryview_func.md
    - Object: builtins/object_func.md
    - Exceptions: builtins/exceptions.md
    - Dir: builtins/dir.md
    - Getattr: builtins/getattr.md
    - Hasattr: builtins/hasattr.md
    - Setattr: builtins/setattr.md
    - Delattr: builtins/delattr.md
    - Vars: builtins/vars.md
    - Classmethod: builtins/classmethod.md
    - Staticmethod: builtins/staticmethod.md
    - Property: builtins/property.md
    - Super: builtins/super.md
    - None: builtins/none.md
    - True: builtins/true.md
    - False: builtins/false.md
    - NotImplemented: builtins/notimplemented.md
    - Ellipsis: builtins/ellipsis.md
    - Interpreter Info: builtins/interpreter_info.md
    - Exit/Quit: builtins/exit_quit.md
  - Standard Library:
    - Overview: stdlib/index.md
    - ABC: stdlib/abc.md
    - Argparse: stdlib/argparse.md
    - Aifc: stdlib/aifc.md
    - Antigravity: stdlib/antigravity.md
    - Array: stdlib/array.md
    - Ast: stdlib/ast.md
    - Asyncio: stdlib/asyncio.md
    - Asynchat: stdlib/asynchat.md
    - Asyncore: stdlib/asyncore.md
    - Base64: stdlib/base64.md
    - Bdb: stdlib/bdb.md
    - Binascii: stdlib/binascii.md
    - Bz2: stdlib/bz2.md
    - Bisect: stdlib/bisect.md
    - Chunk: stdlib/chunk.md
    - Cmd: stdlib/cmd.md
    - Code: stdlib/code.md
    - Codeop: stdlib/codeop.md
    - Collections: stdlib/collections.md
    - Codecs: stdlib/codecs.md
    - Compileall: stdlib/compileall.md
    - Configparser: stdlib/configparser.md
    - Concurrent: stdlib/concurrent.md
    - Concurrent.futures: stdlib/concurrent_futures.md
    - Contextvars: stdlib/contextvars.md
    - Contextlib: stdlib/contextlib.md
    - Copyreg: stdlib/copyreg.md
    - CProfile: stdlib/cprofile.md
    - Cgi: stdlib/cgi.md
    - Cgitb: stdlib/cgitb.md
    - Crypt: stdlib/crypt.md
    - Ctypes: stdlib/ctypes.md
    - Copy: stdlib/copy.md
    - Counter: stdlib/counter.md
    - Curses: stdlib/curses.md
    - Calendar: stdlib/calendar.md
    - Colorsys: stdlib/colorsys.md
    - Csv: stdlib/csv.md
    - Dataclasses: stdlib/dataclasses.md
    - DBM: stdlib/dbm.md
    - Datetime: stdlib/datetime.md
    - Dis: stdlib/dis.md
    - Distutils: stdlib/distutils.md
    - Doctest: stdlib/doctest.md
    - Email: stdlib/email.md
    - Encodings: stdlib/encodings.md
    - Ensurepip: stdlib/ensurepip.md
    - Decimal: stdlib/decimal.md
    - Difflib: stdlib/difflib.md
    - Deque: stdlib/deque.md
    - Defaultdict: stdlib/defaultdict.md
    - Enum: stdlib/enum.md
    - Fcntl: stdlib/fcntl.md
    - Filecmp: stdlib/filecmp.md
    - Fileinput: stdlib/fileinput.md
    - Fnmatch: stdlib/fnmatch.md
    - Fractions: stdlib/fractions.md
    - Ftplib: stdlib/ftplib.md
    - Genericpath: stdlib/genericpath.md
    - Functools: stdlib/functools.md
    - Getopt: stdlib/getopt.md
    - Getpass: stdlib/getpass.md
    - Gettext: stdlib/gettext.md
    - Glob: stdlib/glob.md
    - Imp: stdlib/imp.md
    - Graphlib: stdlib/graphlib.md
    - Html: stdlib/html.md
    - Http: stdlib/http.md
    - Gzip: stdlib/gzip.md
    - Hashlib: stdlib/hashlib.md
    - Heapq: stdlib/heapq.md
    - Hmac: stdlib/hmac.md
    - IO: stdlib/io.md
    - Idlelib: stdlib/idlelib.md
    - Imaplib: stdlib/imaplib.md
    - Imghdr: stdlib/imghdr.md
    - Inspect: stdlib/inspect.md
    - Importlib: stdlib/importlib.md
    - Itertools: stdlib/itertools.md
    - JSON: stdlib/json.md
    - Keyword: stdlib/keyword.md
    - Lib2to3: stdlib/lib2to3.md
    - Linecache: stdlib/linecache.md
    - Locale: stdlib/locale.md
    - Logging: stdlib/logging.md
    - Lzma: stdlib/lzma.md
    - Mailbox: stdlib/mailbox.md
    - Mailcap: stdlib/mailcap.md
    - Marshal: stdlib/marshal.md
    - Mimetypes: stdlib/mimetypes.md
    - Modulefinder: stdlib/modulefinder.md
    - Multiprocessing: stdlib/multiprocessing.md
    - Netrc: stdlib/netrc.md
    - Nntplib: stdlib/nntplib.md
    - Nturl2path: stdlib/nturl2path.md
    - Opcode: stdlib/opcode.md
    - Optparse: stdlib/optparse.md
    - Pdb: stdlib/pdb.md
    - Pickle: stdlib/pickle.md
    - Pickletools: stdlib/pickletools.md
    - Pipes: stdlib/pipes.md
    - Plistlib: stdlib/plistlib.md
    - Pkgutil: stdlib/pkgutil.md
    - Poplib: stdlib/poplib.md
    - Profile: stdlib/profile.md
    - Pstats: stdlib/pstats.md
    - Pyclbr: stdlib/pyclbr.md
    - Pydoc: stdlib/pydoc.md
    - Pydoc_data: stdlib/pydoc_data.md
    - Py_compile: stdlib/py_compile.md
    - Namedtuple: stdlib/namedtuple.md
    - Numbers: stdlib/numbers.md
    - Ntpath: stdlib/ntpath.md
    - Operator: stdlib/operator.md
    - OrderedDict: stdlib/ordereddict.md
    - OS: stdlib/os.md
    - Platform: stdlib/platform.md
    - Pathlib: stdlib/pathlib.md
    - Posixpath: stdlib/posixpath.md
    - Pprint: stdlib/pprint.md
    - Pty: stdlib/pty.md
    - Queue: stdlib/queue.md
    - Quopri: stdlib/quopri.md
    - Readline: stdlib/readline.md
    - Reprlib: stdlib/reprlib.md
    - Rlcompleter: stdlib/rlcompleter.md
    - Runpy: stdlib/runpy.md
    - Sched: stdlib/sched.md
    - Shlex: stdlib/shlex.md
    - Shutil: stdlib/shutil.md
    - Random: stdlib/random.md
    - Regular Expressions: stdlib/re.md
    - Ipaddress: stdlib/ipaddress.md
    - Selectors: stdlib/selectors.md
    - Signal: stdlib/signal.md
    - Site: stdlib/site.md
    - Socket: stdlib/socket.md
    - Socketserver: stdlib/socketserver.md
    - Secrets: stdlib/secrets.md
    - Shelve: stdlib/shelve.md
    - Smtpd: stdlib/smtpd.md
    - Smtplib: stdlib/smtplib.md
    - Sndhdr: stdlib/sndhdr.md
    - Sre_compile: stdlib/sre_compile.md
    - Sre_constants: stdlib/sre_constants.md
    - Sre_parse: stdlib/sre_parse.md
    - Ssl: stdlib/ssl.md
    - Stat: stdlib/stat.md
    - Statistics: stdlib/statistics.md
    - String: stdlib/string.md
    - Stringprep: stdlib/stringprep.md
    - Tabnanny: stdlib/tabnanny.md
    - Sqlite3: stdlib/sqlite3.md
    - Struct: stdlib/struct.md
    - Subprocess: stdlib/subprocess.md
    - Sunau: stdlib/sunau.md
    - Symtable: stdlib/symtable.md
    - Sys: stdlib/sys.md
    - Sysconfig: stdlib/sysconfig.md
    - Tarfile: stdlib/tarfile.md
    - Tempfile: stdlib/tempfile.md
    - Telnetlib: stdlib/telnetlib.md
    - Termios: stdlib/termios.md
    - Token: stdlib/token.md
    - Tokenize: stdlib/tokenize.md
    - Trace: stdlib/trace.md
    - Traceback: stdlib/traceback.md
    - Textwrap: stdlib/textwrap.md
    - Threading: stdlib/threading.md
    - Tomllib: stdlib/tomllib.md
    - Tracemalloc: stdlib/tracemalloc.md
    - This: stdlib/this.md
    - Tkinter: stdlib/tkinter.md
    - Turtle: stdlib/turtle.md
    - Tty: stdlib/tty.md
    - Types: stdlib/types.md
    - Typing: stdlib/typing.md
    - Timeit: stdlib/timeit.md
    - Unittest: stdlib/unittest.md
    - Uuid: stdlib/uuid.md
    - Urllib: stdlib/urllib.md
    - Uu: stdlib/uu.md
    - Venv: stdlib/venv.md
    - Warnings: stdlib/warnings.md
    - Wave: stdlib/wave.md
    - Weakref: stdlib/weakref.md
    - Webbrowser: stdlib/webbrowser.md
    - Wsgiref: stdlib/wsgiref.md
    - Xml: stdlib/xml.md
    - Xmlrpc: stdlib/xmlrpc.md
    - Xdrlib: stdlib/xdrlib.md
    - Zlib: stdlib/zlib.md
    - Zipfile: stdlib/zipfile.md
    - Zipapp: stdlib/zipapp.md
    - Zipimport: stdlib/zipimport.md
    - Zoneinfo: stdlib/zoneinfo.md
  - Implementations:
    - Overview: implementations/index.md
    - CPython: implementations/cpython.md
    - PyPy: implementations/pypy.md
    - Jython: implementations/jython.md
  - Versions:
    - Overview: versions/index.md
    - Python 3.12: versions/py312.md
    - Python 3.11: versions/py311.md
    - Python 3.10: versions/py310.md

plugins:
  - search
  - mermaid2

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - tables
  - toc:
      permalink: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/heikkitoivonen/python-time-space-complexity

copyright: Copyright &copy; 2026
